In [341]:
import pandas as pd
import numpy as np

In [342]:
df = pd.read_excel(r"/Users/jinhyun/Documents/GitHub/Python/UvA projects/Thesis/MSc/data/Process/Process 3 (merge)/merged original_processing_4.xlsx", sheet_name="Sheet1", header=[1])
# df_inf  = pd.read_excel(r"/Users/jinhyun/Documents/GitHub/Python/UvA projects/Thesis/MSc/data/Process/Process 2 (stack)/Inflation_stack.xlsx", sheet_name="Sheet1")
# df_inv  = pd.read_excel(r"/Users/jinhyun/Documents/GitHub/Python/UvA projects/Thesis/MSc/data/Process/Process 2 (stack)/Investment_stack.xlsx", sheet_name="Sheet1")
# df_to   = pd.read_excel(r"/Users/jinhyun/Documents/GitHub/Python/UvA projects/Thesis/MSc/data/Process/Process 2 (stack)/Trade openess.xlsx", sheet_name="Sheet1")

In [343]:
df

,"Adolescent fertility rate (births per 1,000 women ages 15-19)","Agriculture, forestry, and fishing, value added (% of GDP)",Exports of goods and services (% of GDP),"Fertility rate, total (births per woman)","Foreign direct investment, net inflows (BoP, current US$)",GDP (current US$),GDP growth (annual %),Gross capital formation (% of GDP),Imports of goods and services (% of GDP),"Industry (including construction), value added (% of GDP)",...,Mobile cellular subscriptions (per 100 people),"Mortality rate, under-5 (per 1,000 live births)",Population density (people per sq. km of land area),Population growth (annual %),"Population, total","School enrollment, primary (% gross)",Surface area (sq. km),Urban population growth (annual %),Country,Year
0,140.120535,NaN,NaN,6.723308,NaN,2.008272e+10,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,130836765.0,NaN,NaN,NaN,Africa Eastern and Southern,1960
1,140.594564,NaN,NaN,6.738651,NaN,2.050945e+10,NaN,NaN,NaN,NaN,...,NaN,NaN,9.078367,2.539822,134159786.0,NaN,12718531.0,4.211799,Africa Eastern and Southern,1961
2,141.128109,NaN,NaN,6.752818,NaN,2.235043e+10,NaN,NaN,NaN,NaN,...,NaN,NaN,9.312152,2.575182,137614644.0,NaN,12718531.0,4.230380,Africa Eastern and Southern,1962
3,141.323440,NaN,NaN,6.765400,NaN,2.675866e+10,NaN,NaN,NaN,NaN,...,NaN,NaN,9.554904,2.606839,141202036.0,NaN,12718531.0,4.355563,Africa Eastern and Southern,1963
4,141.508160,NaN,NaN,6.775406,NaN,2.446499e+10,NaN,NaN,NaN,NaN,...,NaN,NaN,9.806505,2.633213,144920186.0,NaN,12718531.0,4.458417,Africa Eastern and Southern,1964
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13388,86.135000,8.340969,19.658905,3.707000,3.071877e+08,1.758489e+10,4.709492,9.700147,30.370807,21.404999,...,98.985073,57.0,36.801342,1.459406,14236599.0,98.933189,390760.0,1.276544,Zimbabwe,2017
13389,83.248600,10.520955,28.049757,3.615000,7.178653e+08,1.811554e+10,4.824211,9.687734,41.397264,21.138422,...,89.404869,54.8,37.324058,1.410382,14438812.0,97.750809,390760.0,1.323497,Zimbabwe,2018
13390,80.362200,10.143657,31.251040,3.531000,2.495000e+08,1.928429e+10,-6.144236,7.408702,32.030875,34.691452,...,90.102290,54.2,37.858273,1.421142,14645473.0,97.140213,NaN,1.424249,Zimbabwe,2019
13391,77.475800,7.607101,37.202235,3.460000,1.503600e+08,1.805117e+10,-6.248748,7.451470,38.799703,35.817145,...,88.755806,53.9,38.420388,1.473871,14862927.0,97.304909,NaN,1.573169,Zimbabwe,2020
13392,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Zimbabwe,2021

In [344]:
len(list(df.columns)[:-2])

21

In [345]:
len(list(df.columns))

23

In [346]:
# df2 = df[list(df.columns)[:-2]].isnull().groupby([df['Country']]).transform('sum').astype(int)

In [347]:
# df2 = df.isnull().groupby([df['Country']]).transform('sum')

In [348]:
df2 =  df.isnull().groupby([df['Country']]).sum()

In [349]:
df2

,"Adolescent fertility rate (births per 1,000 women ages 15-19)","Agriculture, forestry, and fishing, value added (% of GDP)",Exports of goods and services (% of GDP),"Fertility rate, total (births per woman)","Foreign direct investment, net inflows (BoP, current US$)",GDP (current US$),GDP growth (annual %),Gross capital formation (% of GDP),Imports of goods and services (% of GDP),"Industry (including construction), value added (% of GDP)",...,Mobile cellular subscriptions (per 100 people),"Mortality rate, under-5 (per 1,000 live births)",Population density (people per sq. km of land area),Population growth (annual %),"Population, total","School enrollment, primary (% gross)",Surface area (sq. km),Urban population growth (annual %),Country,Year
Country,,,,,,,,,,,,,,,,,,,,,
Africa Eastern and Southern,1,22,31,1,11,1,22,35,32,31,...,13,31,2,2,1,62,4,2,0,0
Africa Western and Central,1,22,1,1,11,1,2,22,1,22,...,13,31,2,1,1,62,4,1,0,0
Albania,1,37,21,1,21,25,22,22,21,37,...,13,19,2,2,1,18,4,2,0,0
Algeria,1,40,1,1,11,1,2,1,1,40,...,13,1,2,2,1,12,4,2,0,0
Angola,1,36,41,1,12,21,22,35,41,36,...,13,21,2,2,1,38,4,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
West Bank and Gaza,1,36,35,31,36,35,36,35,35,36,...,37,16,31,32,31,37,4,32,0,0
World,1,10,11,1,11,1,2,11,11,32,...,13,31,2,2,1,12,4,2,0,0
"Yemen, Rep.",1,31,53,1,32,33,34,62,53,31,...,13,1,2,2,1,50,4,2,0,0
Zambia,1,1,35,1,11,1,2,51,35,1,...,13,1,2,2,1,18,4,2,0,0
Zimbabwe,1,6,16,1,11,1,2,1,16,10,...,13,1,2,2,1,21,4,2,0,0

In [350]:
df2.to_excel("nan count.xlsx")

In [351]:
df_del = pd.read_excel(r"/Users/jinhyun/Documents/GitHub/Python/UvA projects/Thesis/MSc/deleting country list.xlsx", sheet_name="Sheet1")

In [352]:
# df_del.to_excel('')

In [353]:
country_check= list(df_del['Country_delete'])

In [354]:
df['Check'] = df['Country'].apply(lambda x:  x in country_check)

In [355]:
df.head(20)

,"Adolescent fertility rate (births per 1,000 women ages 15-19)","Agriculture, forestry, and fishing, value added (% of GDP)",Exports of goods and services (% of GDP),"Fertility rate, total (births per woman)","Foreign direct investment, net inflows (BoP, current US$)",GDP (current US$),GDP growth (annual %),Gross capital formation (% of GDP),Imports of goods and services (% of GDP),"Industry (including construction), value added (% of GDP)",...,"Mortality rate, under-5 (per 1,000 live births)",Population density (people per sq. km of land area),Population growth (annual %),"Population, total","School enrollment, primary (% gross)",Surface area (sq. km),Urban population growth (annual %),Country,Year,Check
0,140.120535,NaN,NaN,6.723308,NaN,2.008272e+10,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,130836765.0,NaN,NaN,NaN,Africa Eastern and Southern,1960,True
1,140.594564,NaN,NaN,6.738651,NaN,2.050945e+10,NaN,NaN,NaN,NaN,...,NaN,9.078367,2.539822,134159786.0,NaN,12718531.0,4.211799,Africa Eastern and Southern,1961,True
2,141.128109,NaN,NaN,6.752818,NaN,2.235043e+10,NaN,NaN,NaN,NaN,...,NaN,9.312152,2.575182,137614644.0,NaN,12718531.0,4.230380,Africa Eastern and Southern,1962,True
3,141.323440,NaN,NaN,6.765400,NaN,2.675866e+10,NaN,NaN,NaN,NaN,...,NaN,9.554904,2.606839,141202036.0,NaN,12718531.0,4.355563,Africa Eastern and Southern,1963,True
4,141.508160,NaN,NaN,6.775406,NaN,2.446499e+10,NaN,NaN,NaN,NaN,...,NaN,9.806505,2.633213,144920186.0,NaN,12718531.0,4.458417,Africa Eastern and Southern,1964,True
5,141.668896,NaN,NaN,6.783357,NaN,2.787894e+10,NaN,NaN,NaN,NaN,...,NaN,10.067014,2.656488,148769974.0,NaN,12718531.0,4.504108,Africa Eastern and Southern,1965,True
6,141.879704,NaN,NaN,6.789885,NaN,3.031384e+10,NaN,NaN,NaN,NaN,...,NaN,10.336516,2.677084,152752671.0,NaN,12718531.0,4.549092,Africa Eastern and Southern,1966,True
7,141.983225,NaN,NaN,6.796040,NaN,3.137555e+10,NaN,NaN,NaN,NaN,...,NaN,10.615566,2.699647,156876454.0,NaN,12718531.0,4.575043,Africa Eastern and Southern,1967,True
8,142.020168,NaN,NaN,6.801478,NaN,3.418718e+10,NaN,NaN,NaN,NaN,...,NaN,10.905185,2.728246,161156430.0,NaN,12718531.0,4.625073,Africa Eastern and Southern,1968,True
9,142.010506,NaN,NaN,6.806248,NaN,3.924842e+10,NaN,NaN,NaN,NaN,...,NaN,11.206669,2.764600,165611760.0,NaN,12718531.0,4.696248,Africa Eastern and Southern,1969,True
10,142.033458,NaN,NaN,6.810063,4.217099e+08,4.192233e+10,NaN,NaN,NaN,NaN,...,NaN,11.521018,2.805012,170257189.0,NaN,12718531.0,4.619846,Africa Eastern and Southern,1970,True
11,142.279778,NaN,NaN,6.811403,3.264909e+08,4.624902e+10,NaN,NaN,NaN,NaN,...,NaN,11.848734,2.844507,175100167.0,NaN,12718531.0,4.691015,Africa Eastern and Southern,1971,True
12,142.629356,NaN,NaN,6.810668,2.188882e+08,5.022625e+10,NaN,NaN,NaN,NaN,...,NaN,12.189849,2.878913,180141148.0,NaN,12718531.0,4.784020,Africa Eastern and Southern,1972,True
13,142.469778,NaN,NaN,6.806765,1.765591e+08,6.549333e+10,NaN,NaN,NaN,NaN,...,NaN,12.544120,2.906278,185376550.0,NaN,12718531.0,4.771458,Africa Eastern and Southern,1973,True
14,142.290486,NaN,NaN,6.799593,8.985156e+08,8.136911e+10,NaN,NaN,NaN,NaN,...,NaN,12.911169,2.926069,190800796.0,NaN,12718531.0,4.709800,Africa Eastern and Southern,1974,True
15,142.053901,NaN,NaN,6.789526,3.168347e+08,8.676040e+10,NaN,NaN,NaN,NaN,...,NaN,13.290730,2.939789,196409937.0,NaN,12718531.0,4.767423,Africa Eastern and Southern,1975,True
16,141.730609,NaN,NaN,6.776643,4.112611e+08,8.652629e+10,NaN,NaN,NaN,NaN,...,NaN,13.682924,2.950884,202205766.0,NaN,12718531.0,4.812808,Africa Eastern and Southern,1976,True
17,141.396423,NaN,NaN,6.763316,6.710362e+07,9.877417e+10,NaN,NaN,NaN,NaN,...,NaN,14.088073,2.960983,208193045.0,NaN,12718531.0,4.853856,Africa Eastern and Southern,1977,True
18,140.774087,NaN,NaN,6.748156,1.684391e+08,1.105839e+11,NaN,NaN,NaN,NaN,...,NaN,14.505949,2.966164,214368393.0,NaN,12718531.0,4.862695,Africa Eastern and Southern,1978,True
19,140.150094,NaN,NaN,6.731254,-1.231237e+07,1.294594e+11,NaN,NaN,NaN,NaN,...,NaN,14.937131,2.972449,220740384.0,NaN,12718531.0,4.661588,Africa Eastern and Southern,1979,True

In [356]:
df3 = df.loc[df['Check'] == False]

In [357]:
df3.head(30)

,"Adolescent fertility rate (births per 1,000 women ages 15-19)","Agriculture, forestry, and fishing, value added (% of GDP)",Exports of goods and services (% of GDP),"Fertility rate, total (births per woman)","Foreign direct investment, net inflows (BoP, current US$)",GDP (current US$),GDP growth (annual %),Gross capital formation (% of GDP),Imports of goods and services (% of GDP),"Industry (including construction), value added (% of GDP)",...,"Mortality rate, under-5 (per 1,000 live births)",Population density (people per sq. km of land area),Population growth (annual %),"Population, total","School enrollment, primary (% gross)",Surface area (sq. km),Urban population growth (annual %),Country,Year,Check
186,123.8892,NaN,39.043173,7.524,NaN,2.723593e+09,NaN,42.184577,67.143632,NaN,...,241.1,NaN,NaN,11057864.0,NaN,NaN,NaN,Algeria,1960,False
187,124.7566,NaN,46.244557,7.573,NaN,2.434727e+09,-13.605441,47.189529,67.503771,NaN,...,241.2,4.759687,2.487129,11336336.0,NaN,2381740.0,6.618890,Algeria,1961,False
188,125.6240,NaN,19.793873,7.614,NaN,2.001428e+09,-19.685042,35.420613,20.818647,NaN,...,241.7,4.878714,2.469981,11619828.0,NaN,2381740.0,6.829935,Algeria,1962,False
189,123.5016,NaN,24.684682,7.646,NaN,2.702960e+09,34.313729,28.940662,36.825515,NaN,...,242.6,5.001721,2.490050,11912800.0,NaN,2381740.0,6.757299,Algeria,1963,False
190,121.3792,NaN,25.084059,7.665,NaN,2.909293e+09,5.839413,21.846608,29.439763,NaN,...,243.5,5.131406,2.559756,12221675.0,NaN,2381740.0,6.738157,Algeria,1964,False
191,119.2568,NaN,22.603944,7.675,NaN,3.136259e+09,6.206898,22.603944,25.833078,NaN,...,244.5,5.269626,2.657977,12550880.0,NaN,2381740.0,6.729878,Algeria,1965,False
192,117.1344,NaN,25.986198,7.676,NaN,3.039835e+09,-4.804971,17.324132,24.653572,NaN,...,245.2,5.417311,2.764007,12902626.0,NaN,2381740.0,5.894366,Algeria,1966,False
193,115.0120,NaN,23.434417,7.672,NaN,3.370843e+09,9.452963,23.434417,21.631769,NaN,...,245.2,5.573665,2.845322,13275020.0,NaN,2381740.0,3.266680,Algeria,1967,False
194,112.6814,NaN,23.135635,7.666,NaN,3.852116e+09,10.796239,27.867922,24.187254,NaN,...,244.2,5.736806,2.884990,13663581.0,NaN,2381740.0,3.307126,Algeria,1968,False
195,110.3508,NaN,23.788777,7.656,NaN,4.257219e+09,8.433280,32.352736,28.070758,NaN,...,242.0,5.903971,2.872252,14061724.0,NaN,2381740.0,3.292629,Algeria,1969,False
196,108.0202,NaN,22.072733,7.643,8.012000e+07,4.863487e+09,8.862657,36.649069,29.152668,NaN,...,238.5,6.073288,2.827489,14464992.0,NaN,2381740.0,3.248622,Algeria,1970,False
197,105.6896,NaN,18.442519,7.624,6.000000e+05,5.077222e+09,-11.331719,35.281342,27.663778,NaN,...,233.6,6.244281,2.776588,14872253.0,74.465683,2381740.0,3.193434,Algeria,1971,False
198,103.3590,NaN,20.449562,7.597,4.149000e+07,6.766767e+09,27.423969,34.302489,25.726868,NaN,...,227.5,6.417994,2.743959,15285992.0,78.602417,2381740.0,3.161586,Algeria,1972,False
199,101.6092,NaN,25.503663,7.558,5.100000e+07,8.707848e+09,3.813176,40.284195,31.589764,NaN,...,220.2,6.595947,2.734984,15709831.0,83.281326,2381740.0,3.150885,Algeria,1973,False
200,99.8594,NaN,38.749044,7.505,3.580000e+08,1.321003e+10,7.494918,40.016534,35.489776,NaN,...,212.1,6.780345,2.757255,16149018.0,87.053101,2381740.0,3.171427,Algeria,1974,False
201,98.1096,NaN,33.688936,7.434,1.190000e+08,1.555793e+10,5.045342,45.406826,42.965599,NaN,...,203.1,6.972930,2.800756,16607706.0,89.160469,2381740.0,3.215704,Algeria,1975,False
202,96.3598,NaN,33.054584,7.344,1.870000e+08,1.772835e+10,8.386756,43.350275,37.118673,NaN,...,193.8,7.173663,2.838085,17085799.0,92.154419,2381740.0,3.251311,Algeria,1976,False
203,94.6100,NaN,30.586567,7.234,1.784526e+08,2.097190e+10,5.258586,46.914735,41.740317,NaN,...,184.0,7.382375,2.867913,17582899.0,94.104607,2381740.0,3.926568,Algeria,1977,False
204,86.0068,NaN,25.535837,7.105,1.351522e+08,2.636449e+10,9.214836,52.219354,40.168732,NaN,...,173.8,7.600437,2.911034,18102266.0,95.151299,2381740.0,5.004868,Algeria,1978,False
205,77.4036,NaN,31.148300,6.957,2.569249e+07,3.324342e+10,7.477827,42.545925,32.865749,NaN,...,162.8,7.829486,2.969111,18647801.0,94.874878,2381740.0,5.031720,Algeria,1979,False
206,68.8004,NaN,34.338461,6.794,3.486690e+08,4.234638e+10,0.790607,39.076922,30.338462,NaN,...,150.0,8.070427,3.030949,19221659.0,94.768150,2381740.0,5.065663,Algeria,1980,False
207,60.1972,NaN,34.587251,6.617,1.320726e+07,4.434867e+10,2.999996,36.990595,30.877743,NaN,...,135.3,8.323451,3.087059,19824297.0,93.683762,2381740.0,5.083442,Algeria,1981,False
208,51.5940,NaN,30.924856,6.430,-5.356919e+07,4.520709e+10,6.400004,37.283237,28.998075,NaN,...,119.2,8.587378,3.121642,20452901.0,92.564789,2381740.0,5.089986,Algeria,1982,False
209,47.8858,NaN,27.941806,6.237,4.176412e+05,4.880137e+10,5.400003,37.569533,25.802311,NaN,...,102.8,8.859857,3.123717,21101875.0,91.363029,2381740.0,5.060555,Algeria,1983,False
210,44.1776,NaN,25.710016,6.038,8.026689e+05,5.369828e+10,5.599997,35.164424,27.466368,NaN,...,87.3,9.137680,3.087594,21763578.0,90.952621,2381740.0,4.996132,Algeria,1984,False
211,40.4694,NaN,23.583933,5.835,3.977883e+05,5.793787e+10,3.699997,34.569172,26.742188,NaN,...,74.5,9.418117,3.022869,22431507.0,90.083588,2381740.0,4.893574,Algeria,1985,False
212,36.7612,NaN,12.854757,5.627,5.316528e+06,6.369224e+10,0.400001,33.555925,23.171953,NaN,...,65.0,9.699793,2.946937,23102386.0,89.046356,2381740.0,4.789436,Algeria,1986,False
213,33.0530,NaN,14.272475,5.412,3.711538e+06,6.674640e+10,-0.699998,27.556379,18.412110,NaN,...,58.4,9.981899,2.866872,23774287.0,90.245399,2381740.0,4.615713,Algeria,1987,False
214,31.3024,NaN,15.507868,5.191,1.301827e+07,5.908907e+10,-1.000005,27.639485,22.603719,NaN,...,53.9,10.262863,2.775857,24443472.0,91.756790,2381740.0,4.350220,Algeria,1988,False
215,29.5518,NaN,18.639263,4.962,1.209165e+07,5.563441e+10,4.400002,30.073234,28.514056,NaN,...,51.0,10.541114,2.675132,25106192.0,92.002853,2381740.0,4.221194,Algeria,1989,False

In [358]:
df3.to_excel('data_colleted_raw.xlsx')

In [359]:
df3.fillna( method ='bfill', inplace = True)
df3.head(30)

/Users/jinhyun/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:5176: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

,"Adolescent fertility rate (births per 1,000 women ages 15-19)","Agriculture, forestry, and fishing, value added (% of GDP)",Exports of goods and services (% of GDP),"Fertility rate, total (births per woman)","Foreign direct investment, net inflows (BoP, current US$)",GDP (current US$),GDP growth (annual %),Gross capital formation (% of GDP),Imports of goods and services (% of GDP),"Industry (including construction), value added (% of GDP)",...,"Mortality rate, under-5 (per 1,000 live births)",Population density (people per sq. km of land area),Population growth (annual %),"Population, total","School enrollment, primary (% gross)",Surface area (sq. km),Urban population growth (annual %),Country,Year,Check
186,123.8892,11.10698,39.043173,7.524,8.012000e+07,2.723593e+09,-13.605441,42.184577,67.143632,35.860933,...,241.1,4.759687,2.487129,11057864.0,74.465683,2381740.0,6.618890,Algeria,1960,False
187,124.7566,11.10698,46.244557,7.573,8.012000e+07,2.434727e+09,-13.605441,47.189529,67.503771,35.860933,...,241.2,4.759687,2.487129,11336336.0,74.465683,2381740.0,6.618890,Algeria,1961,False
188,125.6240,11.10698,19.793873,7.614,8.012000e+07,2.001428e+09,-19.685042,35.420613,20.818647,35.860933,...,241.7,4.878714,2.469981,11619828.0,74.465683,2381740.0,6.829935,Algeria,1962,False
189,123.5016,11.10698,24.684682,7.646,8.012000e+07,2.702960e+09,34.313729,28.940662,36.825515,35.860933,...,242.6,5.001721,2.490050,11912800.0,74.465683,2381740.0,6.757299,Algeria,1963,False
190,121.3792,11.10698,25.084059,7.665,8.012000e+07,2.909293e+09,5.839413,21.846608,29.439763,35.860933,...,243.5,5.131406,2.559756,12221675.0,74.465683,2381740.0,6.738157,Algeria,1964,False
191,119.2568,11.10698,22.603944,7.675,8.012000e+07,3.136259e+09,6.206898,22.603944,25.833078,35.860933,...,244.5,5.269626,2.657977,12550880.0,74.465683,2381740.0,6.729878,Algeria,1965,False
192,117.1344,11.10698,25.986198,7.676,8.012000e+07,3.039835e+09,-4.804971,17.324132,24.653572,35.860933,...,245.2,5.417311,2.764007,12902626.0,74.465683,2381740.0,5.894366,Algeria,1966,False
193,115.0120,11.10698,23.434417,7.672,8.012000e+07,3.370843e+09,9.452963,23.434417,21.631769,35.860933,...,245.2,5.573665,2.845322,13275020.0,74.465683,2381740.0,3.266680,Algeria,1967,False
194,112.6814,11.10698,23.135635,7.666,8.012000e+07,3.852116e+09,10.796239,27.867922,24.187254,35.860933,...,244.2,5.736806,2.884990,13663581.0,74.465683,2381740.0,3.307126,Algeria,1968,False
195,110.3508,11.10698,23.788777,7.656,8.012000e+07,4.257219e+09,8.433280,32.352736,28.070758,35.860933,...,242.0,5.903971,2.872252,14061724.0,74.465683,2381740.0,3.292629,Algeria,1969,False
196,108.0202,11.10698,22.072733,7.643,8.012000e+07,4.863487e+09,8.862657,36.649069,29.152668,35.860933,...,238.5,6.073288,2.827489,14464992.0,74.465683,2381740.0,3.248622,Algeria,1970,False
197,105.6896,11.10698,18.442519,7.624,6.000000e+05,5.077222e+09,-11.331719,35.281342,27.663778,35.860933,...,233.6,6.244281,2.776588,14872253.0,74.465683,2381740.0,3.193434,Algeria,1971,False
198,103.3590,11.10698,20.449562,7.597,4.149000e+07,6.766767e+09,27.423969,34.302489,25.726868,35.860933,...,227.5,6.417994,2.743959,15285992.0,78.602417,2381740.0,3.161586,Algeria,1972,False
199,101.6092,11.10698,25.503663,7.558,5.100000e+07,8.707848e+09,3.813176,40.284195,31.589764,35.860933,...,220.2,6.595947,2.734984,15709831.0,83.281326,2381740.0,3.150885,Algeria,1973,False
200,99.8594,11.10698,38.749044,7.505,3.580000e+08,1.321003e+10,7.494918,40.016534,35.489776,35.860933,...,212.1,6.780345,2.757255,16149018.0,87.053101,2381740.0,3.171427,Algeria,1974,False
201,98.1096,11.10698,33.688936,7.434,1.190000e+08,1.555793e+10,5.045342,45.406826,42.965599,35.860933,...,203.1,6.972930,2.800756,16607706.0,89.160469,2381740.0,3.215704,Algeria,1975,False
202,96.3598,11.10698,33.054584,7.344,1.870000e+08,1.772835e+10,8.386756,43.350275,37.118673,35.860933,...,193.8,7.173663,2.838085,17085799.0,92.154419,2381740.0,3.251311,Algeria,1976,False
203,94.6100,11.10698,30.586567,7.234,1.784526e+08,2.097190e+10,5.258586,46.914735,41.740317,35.860933,...,184.0,7.382375,2.867913,17582899.0,94.104607,2381740.0,3.926568,Algeria,1977,False
204,86.0068,11.10698,25.535837,7.105,1.351522e+08,2.636449e+10,9.214836,52.219354,40.168732,35.860933,...,173.8,7.600437,2.911034,18102266.0,95.151299,2381740.0,5.004868,Algeria,1978,False
205,77.4036,11.10698,31.148300,6.957,2.569249e+07,3.324342e+10,7.477827,42.545925,32.865749,35.860933,...,162.8,7.829486,2.969111,18647801.0,94.874878,2381740.0,5.031720,Algeria,1979,False
206,68.8004,11.10698,34.338461,6.794,3.486690e+08,4.234638e+10,0.790607,39.076922,30.338462,35.860933,...,150.0,8.070427,3.030949,19221659.0,94.768150,2381740.0,5.065663,Algeria,1980,False
207,60.1972,11.10698,34.587251,6.617,1.320726e+07,4.434867e+10,2.999996,36.990595,30.877743,35.860933,...,135.3,8.323451,3.087059,19824297.0,93.683762,2381740.0,5.083442,Algeria,1981,False
208,51.5940,11.10698,30.924856,6.430,-5.356919e+07,4.520709e+10,6.400004,37.283237,28.998075,35.860933,...,119.2,8.587378,3.121642,20452901.0,92.564789,2381740.0,5.089986,Algeria,1982,False
209,47.8858,11.10698,27.941806,6.237,4.176412e+05,4.880137e+10,5.400003,37.569533,25.802311,35.860933,...,102.8,8.859857,3.123717,21101875.0,91.363029,2381740.0,5.060555,Algeria,1983,False
210,44.1776,11.10698,25.710016,6.038,8.026689e+05,5.369828e+10,5.599997,35.164424,27.466368,35.860933,...,87.3,9.137680,3.087594,21763578.0,90.952621,2381740.0,4.996132,Algeria,1984,False
211,40.4694,11.10698,23.583933,5.835,3.977883e+05,5.793787e+10,3.699997,34.569172,26.742188,35.860933,...,74.5,9.418117,3.022869,22431507.0,90.083588,2381740.0,4.893574,Algeria,1985,False
212,36.7612,11.10698,12.854757,5.627,5.316528e+06,6.369224e+10,0.400001,33.555925,23.171953,35.860933,...,65.0,9.699793,2.946937,23102386.0,89.046356,2381740.0,4.789436,Algeria,1986,False
213,33.0530,11.10698,14.272475,5.412,3.711538e+06,6.674640e+10,-0.699998,27.556379,18.412110,35.860933,...,58.4,9.981899,2.866872,23774287.0,90.245399,2381740.0,4.615713,Algeria,1987,False
214,31.3024,11.10698,15.507868,5.191,1.301827e+07,5.908907e+10,-1.000005,27.639485,22.603719,35.860933,...,53.9,10.262863,2.775857,24443472.0,91.756790,2381740.0,4.350220,Algeria,1988,False
215,29.5518,11.10698,18.639263,4.962,1.209165e+07,5.563441e+10,4.400002,30.073234,28.514056,35.860933,...,51.0,10.541114,2.675132,25106192.0,92.002853,2381740.0,4.221194,Algeria,1989,False

In [360]:
df3.to_excel('data_raw_miss_bfill.xlsx')

In [361]:
df3.fillna( method ='ffill', inplace = True)
df3.head(30)

/Users/jinhyun/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:5176: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

,"Adolescent fertility rate (births per 1,000 women ages 15-19)","Agriculture, forestry, and fishing, value added (% of GDP)",Exports of goods and services (% of GDP),"Fertility rate, total (births per woman)","Foreign direct investment, net inflows (BoP, current US$)",GDP (current US$),GDP growth (annual %),Gross capital formation (% of GDP),Imports of goods and services (% of GDP),"Industry (including construction), value added (% of GDP)",...,"Mortality rate, under-5 (per 1,000 live births)",Population density (people per sq. km of land area),Population growth (annual %),"Population, total","School enrollment, primary (% gross)",Surface area (sq. km),Urban population growth (annual %),Country,Year,Check
186,123.8892,11.10698,39.043173,7.524,8.012000e+07,2.723593e+09,-13.605441,42.184577,67.143632,35.860933,...,241.1,4.759687,2.487129,11057864.0,74.465683,2381740.0,6.618890,Algeria,1960,False
187,124.7566,11.10698,46.244557,7.573,8.012000e+07,2.434727e+09,-13.605441,47.189529,67.503771,35.860933,...,241.2,4.759687,2.487129,11336336.0,74.465683,2381740.0,6.618890,Algeria,1961,False
188,125.6240,11.10698,19.793873,7.614,8.012000e+07,2.001428e+09,-19.685042,35.420613,20.818647,35.860933,...,241.7,4.878714,2.469981,11619828.0,74.465683,2381740.0,6.829935,Algeria,1962,False
189,123.5016,11.10698,24.684682,7.646,8.012000e+07,2.702960e+09,34.313729,28.940662,36.825515,35.860933,...,242.6,5.001721,2.490050,11912800.0,74.465683,2381740.0,6.757299,Algeria,1963,False
190,121.3792,11.10698,25.084059,7.665,8.012000e+07,2.909293e+09,5.839413,21.846608,29.439763,35.860933,...,243.5,5.131406,2.559756,12221675.0,74.465683,2381740.0,6.738157,Algeria,1964,False
191,119.2568,11.10698,22.603944,7.675,8.012000e+07,3.136259e+09,6.206898,22.603944,25.833078,35.860933,...,244.5,5.269626,2.657977,12550880.0,74.465683,2381740.0,6.729878,Algeria,1965,False
192,117.1344,11.10698,25.986198,7.676,8.012000e+07,3.039835e+09,-4.804971,17.324132,24.653572,35.860933,...,245.2,5.417311,2.764007,12902626.0,74.465683,2381740.0,5.894366,Algeria,1966,False
193,115.0120,11.10698,23.434417,7.672,8.012000e+07,3.370843e+09,9.452963,23.434417,21.631769,35.860933,...,245.2,5.573665,2.845322,13275020.0,74.465683,2381740.0,3.266680,Algeria,1967,False
194,112.6814,11.10698,23.135635,7.666,8.012000e+07,3.852116e+09,10.796239,27.867922,24.187254,35.860933,...,244.2,5.736806,2.884990,13663581.0,74.465683,2381740.0,3.307126,Algeria,1968,False
195,110.3508,11.10698,23.788777,7.656,8.012000e+07,4.257219e+09,8.433280,32.352736,28.070758,35.860933,...,242.0,5.903971,2.872252,14061724.0,74.465683,2381740.0,3.292629,Algeria,1969,False
196,108.0202,11.10698,22.072733,7.643,8.012000e+07,4.863487e+09,8.862657,36.649069,29.152668,35.860933,...,238.5,6.073288,2.827489,14464992.0,74.465683,2381740.0,3.248622,Algeria,1970,False
197,105.6896,11.10698,18.442519,7.624,6.000000e+05,5.077222e+09,-11.331719,35.281342,27.663778,35.860933,...,233.6,6.244281,2.776588,14872253.0,74.465683,2381740.0,3.193434,Algeria,1971,False
198,103.3590,11.10698,20.449562,7.597,4.149000e+07,6.766767e+09,27.423969,34.302489,25.726868,35.860933,...,227.5,6.417994,2.743959,15285992.0,78.602417,2381740.0,3.161586,Algeria,1972,False
199,101.6092,11.10698,25.503663,7.558,5.100000e+07,8.707848e+09,3.813176,40.284195,31.589764,35.860933,...,220.2,6.595947,2.734984,15709831.0,83.281326,2381740.0,3.150885,Algeria,1973,False
200,99.8594,11.10698,38.749044,7.505,3.580000e+08,1.321003e+10,7.494918,40.016534,35.489776,35.860933,...,212.1,6.780345,2.757255,16149018.0,87.053101,2381740.0,3.171427,Algeria,1974,False
201,98.1096,11.10698,33.688936,7.434,1.190000e+08,1.555793e+10,5.045342,45.406826,42.965599,35.860933,...,203.1,6.972930,2.800756,16607706.0,89.160469,2381740.0,3.215704,Algeria,1975,False
202,96.3598,11.10698,33.054584,7.344,1.870000e+08,1.772835e+10,8.386756,43.350275,37.118673,35.860933,...,193.8,7.173663,2.838085,17085799.0,92.154419,2381740.0,3.251311,Algeria,1976,False
203,94.6100,11.10698,30.586567,7.234,1.784526e+08,2.097190e+10,5.258586,46.914735,41.740317,35.860933,...,184.0,7.382375,2.867913,17582899.0,94.104607,2381740.0,3.926568,Algeria,1977,False
204,86.0068,11.10698,25.535837,7.105,1.351522e+08,2.636449e+10,9.214836,52.219354,40.168732,35.860933,...,173.8,7.600437,2.911034,18102266.0,95.151299,2381740.0,5.004868,Algeria,1978,False
205,77.4036,11.10698,31.148300,6.957,2.569249e+07,3.324342e+10,7.477827,42.545925,32.865749,35.860933,...,162.8,7.829486,2.969111,18647801.0,94.874878,2381740.0,5.031720,Algeria,1979,False
206,68.8004,11.10698,34.338461,6.794,3.486690e+08,4.234638e+10,0.790607,39.076922,30.338462,35.860933,...,150.0,8.070427,3.030949,19221659.0,94.768150,2381740.0,5.065663,Algeria,1980,False
207,60.1972,11.10698,34.587251,6.617,1.320726e+07,4.434867e+10,2.999996,36.990595,30.877743,35.860933,...,135.3,8.323451,3.087059,19824297.0,93.683762,2381740.0,5.083442,Algeria,1981,False
208,51.5940,11.10698,30.924856,6.430,-5.356919e+07,4.520709e+10,6.400004,37.283237,28.998075,35.860933,...,119.2,8.587378,3.121642,20452901.0,92.564789,2381740.0,5.089986,Algeria,1982,False
209,47.8858,11.10698,27.941806,6.237,4.176412e+05,4.880137e+10,5.400003,37.569533,25.802311,35.860933,...,102.8,8.859857,3.123717,21101875.0,91.363029,2381740.0,5.060555,Algeria,1983,False
210,44.1776,11.10698,25.710016,6.038,8.026689e+05,5.369828e+10,5.599997,35.164424,27.466368,35.860933,...,87.3,9.137680,3.087594,21763578.0,90.952621,2381740.0,4.996132,Algeria,1984,False
211,40.4694,11.10698,23.583933,5.835,3.977883e+05,5.793787e+10,3.699997,34.569172,26.742188,35.860933,...,74.5,9.418117,3.022869,22431507.0,90.083588,2381740.0,4.893574,Algeria,1985,False
212,36.7612,11.10698,12.854757,5.627,5.316528e+06,6.369224e+10,0.400001,33.555925,23.171953,35.860933,...,65.0,9.699793,2.946937,23102386.0,89.046356,2381740.0,4.789436,Algeria,1986,False
213,33.0530,11.10698,14.272475,5.412,3.711538e+06,6.674640e+10,-0.699998,27.556379,18.412110,35.860933,...,58.4,9.981899,2.866872,23774287.0,90.245399,2381740.0,4.615713,Algeria,1987,False
214,31.3024,11.10698,15.507868,5.191,1.301827e+07,5.908907e+10,-1.000005,27.639485,22.603719,35.860933,...,53.9,10.262863,2.775857,24443472.0,91.756790,2381740.0,4.350220,Algeria,1988,False
215,29.5518,11.10698,18.639263,4.962,1.209165e+07,5.563441e+10,4.400002,30.073234,28.514056,35.860933,...,51.0,10.541114,2.675132,25106192.0,92.002853,2381740.0,4.221194,Algeria,1989,False

In [362]:
df3.to_excel('data_raw_miss_b_ffill.xlsx')

In [363]:
df3.isnull().sum()

Adolescent fertility rate (births per 1,000 women ages 15-19)    0
Agriculture, forestry, and fishing, value added (% of GDP)       0
Exports of goods and services (% of GDP)                         0
Fertility rate, total (births per woman)                         0
Foreign direct investment, net inflows (BoP, current US$)        0
GDP (current US$)                                                0
GDP growth (annual %)                                            0
Gross capital formation (% of GDP)                               0
Imports of goods and services (% of GDP)                         0
Industry (including construction), value added (% of GDP)        0
Inflation, GDP deflator (annual %)                               0
Life expectancy at birth, total (years)                          0
Merchandise trade (% of GDP)                                     0
Mobile cellular subscriptions (per 100 people)                   0
Mortality rate, under-5 (per 1,000 live births)                  0
Population density (people per sq. km of land area)              0
Population growth (annual %)                                     0
Population, total                                                0
School enrollment, primary (% gross)                             0
Surface area (sq. km)                                            0
Urban population growth (annual %)                               0
Country                                                          0
Year                                                             0
Check                                                            0
dtype: int64